/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('tdesign-icons-vue-next')['AddIcon']
    AppIcon: typeof import('tdesign-icons-vue-next')['AppIcon']
    Button: typeof import('tdesign-mobile-vue')['Button']
    Cell: typeof import('tdesign-mobile-vue')['Cell']
    CheckCircleIcon: typeof import('tdesign-icons-vue-next')['CheckCircleIcon']
    ChevronLeftIcon: typeof import('tdesign-icons-vue-next')['ChevronLeftIcon']
    ChevronRightIcon: typeof import('tdesign-icons-vue-next')['ChevronRightIcon']
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    CodeIcon: typeof import('tdesign-icons-vue-next')['CodeIcon']
    DeleteIcon: typeof import('tdesign-icons-vue-next')['DeleteIcon']
    DownloadIcon: typeof import('tdesign-icons-vue-next')['DownloadIcon']
    Edit1Icon: typeof import('tdesign-icons-vue-next')['Edit1Icon']
    Loading: typeof import('tdesign-mobile-vue')['Loading']
    PlayCircleIcon: typeof import('tdesign-icons-vue-next')['PlayCircleIcon']
    Progress: typeof import('tdesign-mobile-vue')['Progress']
    PullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh']
    Search: typeof import('tdesign-mobile-vue')['Search']
    StopCircleIcon: typeof import('tdesign-icons-vue-next')['StopCircleIcon']
    Switch: typeof import('tdesign-mobile-vue')['Switch']
    TabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    Tag: typeof import('tdesign-mobile-vue')['Tag']
    VersionPickerDrawer: typeof import('./components/VersionPickerDrawer.vue')['default']
  }
}
